# Generated by Django 5.0.1 on 2024-02-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved_ques',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='uploads/None'),
        ),
    ]
