# Generated by Django 5.0.1 on 2024-02-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_solved_ques_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solved_ques',
            name='file',
        ),
        migrations.AddField(
            model_name='solved_ques',
            name='path',
            field=models.CharField(default='uploads/username/filename.format name', max_length=255),
        ),
    ]
