# Generated by Django 5.0.1 on 2024-02-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_solved_ques_file_solved_ques_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_question', to='main.questions'),
        ),
    ]
