# Generated by Django 5.0.1 on 2024-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stats_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='Acceptance',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)]),
        ),
        migrations.AlterField(
            model_name='stats',
            name='Difficulty',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)]),
        ),
        migrations.AlterField(
            model_name='stats',
            name='Tricky',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)]),
        ),
    ]
