# Generated by Django 5.0.1 on 2024-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_chats_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='no',
            field=models.IntegerField(null=True),
        ),
    ]
