# Generated by Django 5.0.1 on 2024-02-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_stats_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='connections',
        ),
    ]
