# Generated by Django 5.0.1 on 2024-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_following_user_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_title',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
    ]
